templates = [
    { source = "Xresources", target = "~/testing/MyXresourcesTemplate" },
    { source = "Scripts", target = "~/testing/Scripts" }
]

sqldbs = [
    { source = "db.sqlite", target = "~/testing/db.sqlite" }
]

[variables]
fg = "#7e1a7e"
