templates = [ { template = "Xresources", target = "~/testing/Xresources" },
              { template = "db.sqlite", target = "~/testing/db.sqlite" },
              { template = "Scripts", target = "~/testing/Scripts" } ]

[variables]
fg = "#7e1a7e"
