templates = [ { source = "Xresources", target = "~/testing/MyXresourcesTemplate" },
              { source = "db.sqlite", target = "~/testing/db.sqlite" },
              { source = "Scripts", target = "~/testing/Scripts" } ]

[variables]
fg = "#7e1a7e"
